### ISSUE TITLE
unproperly namespaced selector

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-format_remuiformat#10]
some selectors in JS and CSS are too generic and could conflict with others plugins. You should make it more specific by prefixing them with #page-course-view-remuiformat

**Comment by ak4t0sh** [comment]
note : `#teacherCarousel` selector is not valid it should be like `#teacher-carousel`

**Comment by ranjitlawale11** [comment]
Fixed issue, unproperly namespaced selector.

**Comment by ak4t0sh** [comment]
partially fixed.
You forgot to prefix your css selectors which could conflict with other plugins

**Comment by ranjitlawale11** [comment]
Added **#page-course-view-remuiformat** prefix **#teacher-carousel** id selector.

**Comment by ak4t0sh** [comment]
Some CSS selectors are still too generic.
Example :
https://github.com/WisdmLabs/moodle-format_remuiformat/blob/48e20c27aac13339e594282f19e0c355e2353f3a/styles.css#L798
